site_name: Cloud Architecture Docs
theme:
    name: material
    palette:
        primary: 'white'
        accent: 'black'
    font:
        text: 'Segoe UI'
        code: 'Roboto Mono'
    logo: logo/CAD.png  # Path to your logo



extra_css:
    - css/extra.css
